extends: airbnb

plugins:
  - import
  - jasmine

env:
  browser: true
  node: true
  jest: true
  jasmine: true

rules:
  object-curly-spacing: 0
  quotes: 0
  arrow-body-style: 0
  react/forbid-prop-types: 0

globals:
  React: true
  ReactDOM: true
